### ISSUE TITLE
Inconsistent PlTerm assignment semantics

### ISSUE THREAD

**Issue by vmatare** [SWI-Prolog/packages-cpp#3]
The overloaded PlTerm assignment (unification) operator:
`int PlTerm::operator =(const PlTerm &)`
turns out to be a little treacherous in practice. Consider a statement like:
```
PlTerm t1;
PlTerm t2 = t1
```
Contrary to intuition, the second line does not use the overloaded assignment operator, but the copy constructor, and hence no unification is performed. We simply end up with a `t2` that holds the same `term_t` reference as `t1`. That's why modern compilers usually output a warning when the copy assignment operator is overridden, but not the copy constructor.

So, my suggestion would be to make the copy assignment semantics consistent with copy construction. Either both should perform unification or none. I'm leaning towards performing unification in the copy constructor also, since that should be less likely to break existing code. Opinions?

**Comment by sei-mwd** [comment]
The question, in my mind, is if you want to do a unification every time you pass a `PlTerm` by value, which I think is probably undesirable.

**Comment by JanWielemaker** [comment]
Complicated stuff.  An explicit `PlTerm t2 = t1` isn't very meaningful.  Why would you create a new term reference and unify it with an existing one?   It surely unifies (although it may run out of stack), but the end is the same as just using a copy of the term reference.   So, I think a simply copy of the existing reference is the way to go for this (but I'm a lousy C++ programmer ...)

**Comment by vmatare** [comment]
Well, there are certainly many trivial cases where it doesn't matter if we assign or unify. The question is what does/should the user expect in the non-trivial ones? It ultimately comes down to "should copy construction and copy assignment always have the same semantics?"

At the time I probably thought they should, but now I'm not so sure any more. Maybe it's just fine the way it is. After all, `operator =(...)` returns `int`, which should make it clear there's something unconventional going on.

**Comment by vmatare** [comment]
Feel free to close.

**Comment by JanWielemaker** [comment]
Yes, I think it is good as it is.   In retrospect I may have been better to not use `=` for unification (looked so natural) and have t1.unify(t2), but changing that too late.   In practice this doesn't seem to be much of an issue.
